DISEASE_SPECS = {
    "diabetes": {
        "title": "Diabetes Risk Assessment",
        "description": "Estimate diabetes risk from metabolic and demographic indicators.",
        "dataset": "diabetes.csv",
        "target": "Outcome",
        "model_file": "diabetes.joblib",
        "metadata_file": "diabetes_metadata.json",
        "positive_label": 1,
        "threshold": 0.55,
        "features": [
            {"name": "Pregnancies", "label": "Pregnancies", "step": "1", "min": "0", "placeholder": "2"},
            {"name": "Glucose", "label": "Glucose", "step": "1", "min": "0", "placeholder": "120"},
            {"name": "BloodPressure", "label": "Blood Pressure", "step": "1", "min": "0", "placeholder": "80"},
            {"name": "SkinThickness", "label": "Skin Thickness", "step": "1", "min": "0", "placeholder": "20"},
            {"name": "Insulin", "label": "Insulin", "step": "1", "min": "0", "placeholder": "85"},
            {"name": "BMI", "label": "BMI", "step": "0.1", "min": "0", "placeholder": "29.7"},
            {
                "name": "DiabetesPedigreeFunction",
                "label": "Diabetes Pedigree Function",
                "step": "0.001",
                "min": "0",
                "placeholder": "0.45",
            },
            {"name": "Age", "label": "Age", "step": "1", "min": "1", "placeholder": "42"},
        ],
        "highlights": ["Glucose", "BMI", "Age"],
        "tagline": "Metabolic screening",
        "accent": "emerald",
    },
    "heart": {
        "title": "Heart Disease Risk Assessment",
        "description": "Screen cardiovascular risk using common clinical indicators.",
        "dataset": "heart.csv",
        "target": "target",
        "model_file": "heart.joblib",
        "metadata_file": "heart_metadata.json",
        "positive_label": 1,
        "threshold": 0.5,
        "features": [
            {"name": "age", "label": "Age", "step": "1", "min": "1", "placeholder": "54"},
            {"name": "sex", "label": "Sex (1=Male, 0=Female)", "step": "1", "min": "0", "max": "1", "placeholder": "1"},
            {"name": "cp", "label": "Chest Pain Type", "step": "1", "min": "0", "max": "3", "placeholder": "2"},
            {"name": "trestbps", "label": "Resting Blood Pressure", "step": "1", "min": "0", "placeholder": "130"},
            {"name": "chol", "label": "Cholesterol", "step": "1", "min": "0", "placeholder": "246"},
            {"name": "fbs", "label": "Fasting Blood Sugar > 120", "step": "1", "min": "0", "max": "1", "placeholder": "0"},
            {"name": "restecg", "label": "Resting ECG", "step": "1", "min": "0", "max": "2", "placeholder": "1"},
            {"name": "thalach", "label": "Max Heart Rate", "step": "1", "min": "0", "placeholder": "150"},
            {"name": "exang", "label": "Exercise Angina", "step": "1", "min": "0", "max": "1", "placeholder": "0"},
            {"name": "oldpeak", "label": "Oldpeak", "step": "0.1", "placeholder": "1.3"},
            {"name": "slope", "label": "ST Slope", "step": "1", "min": "0", "max": "2", "placeholder": "2"},
            {"name": "ca", "label": "Major Vessels", "step": "1", "min": "0", "max": "4", "placeholder": "0"},
            {"name": "thal", "label": "Thal", "step": "1", "min": "0", "max": "3", "placeholder": "2"},
        ],
        "highlights": ["trestbps", "chol", "thalach"],
        "tagline": "Cardiovascular screening",
        "accent": "coral",
    },
    "liver": {
        "title": "Liver Disease Risk Assessment",
        "description": "Assess liver-related risk using bilirubin and enzyme markers.",
        "dataset": "liver.csv",
        "target": "is_patient",
        "model_file": "liver.joblib",
        "metadata_file": "liver_metadata.json",
        "positive_label": 1,
        "threshold": 0.5,
        "features": [
            {"name": "age", "label": "Age", "step": "1", "min": "1", "placeholder": "45"},
            {"name": "gender", "label": "Gender (Male/Female)", "placeholder": "Male"},
            {"name": "tot_bilirubin", "label": "Total Bilirubin", "step": "0.1", "min": "0", "placeholder": "1.0"},
            {"name": "direct_bilirubin", "label": "Direct Bilirubin", "step": "0.1", "min": "0", "placeholder": "0.4"},
            {"name": "tot_proteins", "label": "Total Proteins", "step": "0.1", "min": "0", "placeholder": "6.8"},
            {"name": "albumin", "label": "Albumin", "step": "0.1", "min": "0", "placeholder": "3.4"},
            {"name": "ag_ratio", "label": "Albumin / Globulin Ratio", "step": "0.01", "min": "0", "placeholder": "1.0"},
            {"name": "sgpt", "label": "SGPT (Alanine Aminotransferase)", "step": "1", "min": "0", "placeholder": "35"},
            {"name": "sgot", "label": "SGOT (Aspartate Aminotransferase)", "step": "1", "min": "0", "placeholder": "40"},
            {"name": "alkphos", "label": "Alkaline Phosphatase", "step": "1", "min": "0", "placeholder": "210"},
        ],
        "highlights": ["tot_bilirubin", "direct_bilirubin", "sgpt"],
        "tagline": "Hepatic screening",
        "accent": "amber",
    },
    "parkinsons": {
        "title": "Parkinson's Risk Assessment",
        "description": "Predict Parkinson's risk using acoustic voice measures.",
        "dataset": "parkinsons.csv",
        "target": "status",
        "model_file": "parkinsons.joblib",
        "metadata_file": "parkinsons_metadata.json",
        "positive_label": 1,
        "threshold": 0.55,
        "features": [
            {"name": "MDVP_Fo", "label": "MDVP Fo", "step": "0.001", "placeholder": "119.9"},
            {"name": "MDVP_Fhi", "label": "MDVP Fhi", "step": "0.001", "placeholder": "157.3"},
            {"name": "MDVP_Flo", "label": "MDVP Flo", "step": "0.001", "placeholder": "75.0"},
            {"name": "Jitter", "label": "Jitter", "step": "0.00001", "placeholder": "0.00784"},
            {"name": "Jitter_Abs", "label": "Jitter Abs", "step": "0.00001", "placeholder": "0.00007"},
            {"name": "MDVP_RAP", "label": "MDVP RAP", "step": "0.00001", "placeholder": "0.00370"},
            {"name": "MDVP_PPQ", "label": "MDVP PPQ", "step": "0.00001", "placeholder": "0.00554"},
            {"name": "Jitter_DDP", "label": "Jitter DDP", "step": "0.00001", "placeholder": "0.01109"},
            {"name": "MDVP_Shimmer", "label": "MDVP Shimmer", "step": "0.00001", "placeholder": "0.04374"},
            {"name": "MDVP_Shimmer_dB", "label": "MDVP Shimmer dB", "step": "0.001", "placeholder": "0.426"},
            {"name": "Shimmer_APQ3", "label": "Shimmer APQ3", "step": "0.00001", "placeholder": "0.02182"},
            {"name": "Shimmer_APQ5", "label": "Shimmer APQ5", "step": "0.00001", "placeholder": "0.03130"},
            {"name": "MDVP_APQ", "label": "MDVP APQ", "step": "0.00001", "placeholder": "0.02971"},
            {"name": "Shimmer_DDA", "label": "Shimmer DDA", "step": "0.00001", "placeholder": "0.06545"},
            {"name": "NHR", "label": "NHR", "step": "0.00001", "placeholder": "0.02211"},
            {"name": "HNR", "label": "HNR", "step": "0.001", "placeholder": "21.033"},
            {"name": "RPDE", "label": "RPDE", "step": "0.00001", "placeholder": "0.41478"},
            {"name": "DFA", "label": "DFA", "step": "0.00001", "placeholder": "0.81528"},
            {"name": "spread1", "label": "Spread 1", "step": "0.00001", "placeholder": "-4.81303"},
            {"name": "spread2", "label": "Spread 2", "step": "0.00001", "placeholder": "0.26648"},
            {"name": "D2", "label": "D2", "step": "0.00001", "placeholder": "2.30144"},
            {"name": "PPE", "label": "PPE", "step": "0.00001", "placeholder": "0.28465"},
        ],
        "highlights": ["Jitter", "MDVP_Shimmer", "PPE"],
        "tagline": "Neurological voice analysis",
        "accent": "indigo",
    },
    "mri": {
        "title": "MRI Analysis",
        "description": "Advanced brain connectivity and white matter analysis using NeuroTract.",
        "tagline": "Neuroimaging & brain mapping",
        "accent": "violet",
        "is_imaging_module": True,
        "external_api": "http://localhost:8001",
        "features": [],
        "highlights": [],
        "threshold": 0.0,
        "positive_label": 0,
        "dataset": "",
        "model_file": "",
        "metadata_file": "",
    },
}

for disease_name, spec in DISEASE_SPECS.items():
    spec["feature_names"] = [feature["name"] for feature in spec["features"]]
    spec["sample_file_name"] = f"{disease_name}_batch_template.csv"
